# Generated by Django 2.2.16 on 2022-11-06 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_comments_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
