# Generated by Django 2.2.28 on 2022-11-12 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20221111_2027'),
        ('reviews', '0003_auto_20221112_1021'),
    ]

    operations = [
    ]
