# Generated by Django 2.2.16 on 2022-11-12 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_merge_20221112_1043'),
        ('reviews', '0003_auto_20221112_1105'),
    ]

    operations = [
    ]
