# Generated by Django 2.2.16 on 2022-11-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_auto_20221103_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('usr', 'user'), ('mdr', 'moderator'), ('adm', 'admin')], default='user', max_length=3),
        ),
    ]
