# Generated by Django 2.2.16 on 2022-11-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_auto_20221104_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'usr'), ('moderator', 'mdr'), ('admin', 'adm')], default='user', max_length=10),
        ),
    ]
