# Generated by Django 2.2.16 on 2022-11-08 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_auto_20221107_2240'),
        ('reviews', '0005_auto_20221106_2000'),
    ]

    operations = [
    ]
